packages:
  - "apps/**/*"
  - "libs/**/*"

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ^5.9.3
  eslint: ^10.0.2
  vitest: ^4.0.15
  tailwindcss: 4.2.0
  tailwind-merge: ^3.5.0
  drizzle-orm: ^0.45.0
  zod: ^4.3.0
  graphql: 16.11.0
  "@types/node": ^25.0.0
  react-hook-form: ^7.71.0
  react-day-picker: 9.12.0
  react-resizable-panels: ^3.0.0
